import { ChildProcess, spawn } from 'child_process';
import { EventEmitter } from 'events';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import pidusage from 'pidusage';
import logger from '../logger.js';
import { getJavaBinary } from './javaManager.js';

export type ServerState = 'OFFLINE' | 'STARTING' | 'RUNNING' | 'STOPPING' | 'CRASHED';

export interface StartServerConfig {
  uuid: string;
  memory: number; // in MB
  cpu?: number;
  port: number;
  javaVersion?: string;
  softwareType?: string;
  softwareVersion?: string;
  serverJarPath?: string;
  autoRestart?: boolean;
  eulaAccepted?: boolean;
  startupFlags?: string;
  onlineMode?: boolean;
  whitelistEnabled?: boolean;
}

interface ManagedProcess {
  process: ChildProcess;
  config: StartServerConfig;
  state: ServerState;
  logBuffer: string[];
  autoRestartCount: number;
  stopRequested: boolean;
  startedAt: Date;
}

const processes = new Map<string, ManagedProcess>();
export const processEvents = new EventEmitter();

const MAX_LOG_BUFFER_SIZE = 250;

export function getServerDir(uuid: string): string {
  const baseDir = resolve(process.cwd(), 'servers', uuid);
  if (!existsSync(baseDir)) {
    mkdirSync(baseDir, { recursive: true });
  }
  // Guarantee subdirectories exist according to target layout
  const subdirs = ['logs', 'plugins', 'mods', 'world', 'backups'];
  for (const dir of subdirs) {
    const full = join(baseDir, dir);
    if (!existsSync(full)) {
      mkdirSync(full, { recursive: true });
    }
  }
  return baseDir;
}

export function prepareServerFiles(config: StartServerConfig): void {
  const dir = getServerDir(config.uuid);

  // 1. EULA
  const eulaPath = join(dir, 'eula.txt');
  if (!existsSync(eulaPath) || config.eulaAccepted !== false) {
    writeFileSync(eulaPath, '# Generated by Kinetictyl\neula=true\n', 'utf8');
  }

  // 2. server.properties editor/generator
  const propsPath = join(dir, 'server.properties');
  let propsText = existsSync(propsPath) ? readFileSync(propsPath, 'utf8') : '';
  const propsMap = new Map<string, string>();

  for (const line of propsText.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx > 0) {
      propsMap.set(trimmed.substring(0, idx).trim(), trimmed.substring(idx + 1).trim());
    }
  }

  propsMap.set('server-port', String(config.port));
  propsMap.set('query.port', String(config.port));
  propsMap.set('server-ip', '0.0.0.0');
  if (config.onlineMode !== undefined) {
    propsMap.set('online-mode', config.onlineMode ? 'true' : 'false');
  }
  if (config.whitelistEnabled !== undefined) {
    propsMap.set('white-list', config.whitelistEnabled ? 'true' : 'false');
  }

  let newProps = '# Minecraft Server Properties\n# Modified by Kinetictyl\n';
  propsMap.forEach((val, key) => {
    newProps += `${key}=${val}\n`;
  });
  writeFileSync(propsPath, newProps, 'utf8');
}

export async function startServer(config: StartServerConfig): Promise<boolean> {
  const { uuid, memory, javaVersion = '17', startupFlags = '' } = config;

  const existing = processes.get(uuid);
  if (existing && existing.state !== 'OFFLINE' && existing.state !== 'CRASHED') {
    logger.warn(`Server ${uuid} is already running or starting.`);
    return false;
  }

  prepareServerFiles(config);

  const serverDir = getServerDir(uuid);
  const javaBinary = getJavaBinary(javaVersion);

  const jarName = config.serverJarPath || 'server.jar';
  const jarPath = join(serverDir, jarName);

  if (!existsSync(jarPath)) {
    throw new Error(`Server JAR file '${jarName}' not found in server directory.`);
  }

  // Java args
  const args: string[] = [`-Xms128M`, `-Xmx${memory}M`];

  if (startupFlags.trim()) {
    args.push(...startupFlags.trim().split(/\s+/));
  }

  args.push('-jar', jarName, 'nogui');

  logger.info(`Launching Minecraft server ${uuid} with ${javaBinary} ${args.join(' ')}`);

  const child = spawn(javaBinary, args, {
    cwd: serverDir,
    env: { ...process.env, MALLOC_ARENA_MAX: '2' },
    stdio: ['pipe', 'pipe', 'pipe'],
  });

  const managed: ManagedProcess = {
    process: child,
    config,
    state: 'STARTING',
    logBuffer: [],
    autoRestartCount: existing ? existing.autoRestartCount : 0,
    stopRequested: false,
    startedAt: new Date(),
  };

  processes.set(uuid, managed);
  processEvents.emit('stateChange', { uuid, state: 'STARTING' });

  const appendLog = (line: string) => {
    managed.logBuffer.push(line);
    if (managed.logBuffer.length > MAX_LOG_BUFFER_SIZE) {
      managed.logBuffer.shift();
    }
    processEvents.emit('log', { uuid, line });

    if (managed.state === 'STARTING') {
      if (line.includes('Done') || line.includes('For help, type') || line.includes('Server started')) {
        managed.state = 'RUNNING';
        processEvents.emit('stateChange', { uuid, state: 'RUNNING' });
      }
    }
  };

  child.stdout?.on('data', (chunk: Buffer) => {
    const lines = chunk.toString('utf8').split('\n');
    for (const l of lines) {
      if (l.trim()) appendLog(l);
    }
  });

  child.stderr?.on('data', (chunk: Buffer) => {
    const lines = chunk.toString('utf8').split('\n');
    for (const l of lines) {
      if (l.trim()) appendLog(`[STDERR] ${l}`);
    }
  });

  child.on('error', (err: Error) => {
    logger.error(`Failed to launch server process ${uuid}:`, err);
    managed.state = 'CRASHED';
    processEvents.emit('stateChange', { uuid, state: 'CRASHED' });
    appendLog(`[SYSTEM] Failed to launch server process: ${err.message}`);
  });

  child.on('exit', (code, signal) => {
    logger.info(`Server process ${uuid} exited with code ${code}, signal ${signal}`);
    const wasGraceful = managed.stopRequested || code === 0;

    if (wasGraceful) {
      managed.state = 'OFFLINE';
      processEvents.emit('stateChange', { uuid, state: 'OFFLINE' });
      appendLog('[SYSTEM] Server stopped successfully.');
    } else {
      managed.state = 'CRASHED';
      processEvents.emit('stateChange', { uuid, state: 'CRASHED' });
      appendLog(`[SYSTEM] Server process crashed (code ${code}, signal ${signal}).`);

      if (config.autoRestart !== false && managed.autoRestartCount < 5) {
        managed.autoRestartCount++;
        appendLog(`[SYSTEM] Auto-restarting server in 5 seconds (attempt ${managed.autoRestartCount}/5)...`);
        setTimeout(() => {
          startServer(config).catch((e) => logger.error(`Auto-restart error for ${uuid}:`, e));
        }, 5000);
      }
    }
  });

  return true;
}

export async function stopServer(uuid: string): Promise<boolean> {
  const managed = processes.get(uuid);
  if (!managed || !managed.process || managed.state === 'OFFLINE') {
    return false;
  }

  managed.stopRequested = true;
  managed.state = 'STOPPING';
  processEvents.emit('stateChange', { uuid, state: 'STOPPING' });

  // Send graceful stop command
  sendCommand(uuid, 'stop');

  // Fallback kill timeout after 20s
  setTimeout(() => {
    if (managed.process && !managed.process.killed && managed.state !== 'OFFLINE') {
      logger.warn(`Server ${uuid} did not stop gracefully in 20s, terminating...`);
      managed.process.kill('SIGKILL');
      managed.state = 'OFFLINE';
      processEvents.emit('stateChange', { uuid, state: 'OFFLINE' });
    }
  }, 20000);

  return true;
}

export async function killServer(uuid: string): Promise<boolean> {
  const managed = processes.get(uuid);
  if (!managed || !managed.process) return false;

  managed.stopRequested = true;
  managed.process.kill('SIGKILL');
  managed.state = 'OFFLINE';
  processEvents.emit('stateChange', { uuid, state: 'OFFLINE' });
  return true;
}

export async function restartServer(uuid: string): Promise<boolean> {
  const managed = processes.get(uuid);
  if (!managed) return false;

  const config = managed.config;
  await stopServer(uuid);

  setTimeout(() => {
    startServer(config).catch((err) => logger.error(`Restart failed for ${uuid}:`, err));
  }, 3000);

  return true;
}

export function sendCommand(uuid: string, command: string): boolean {
  const managed = processes.get(uuid);
  if (!managed || !managed.process || !managed.process.stdin) return false;

  const cleanCmd = command.endsWith('\n') ? command : `${command}\n`;
  managed.process.stdin.write(cleanCmd);
  return true;
}

export function getLogBuffer(uuid: string): string[] {
  const managed = processes.get(uuid);
  return managed ? managed.logBuffer : [];
}

export function getServerStatus(uuid: string): {
  running: boolean;
  state: ServerState;
  pid?: number;
  uptime?: number;
} {
  const managed = processes.get(uuid);
  if (!managed || managed.state === 'OFFLINE' || managed.state === 'CRASHED') {
    return { running: false, state: managed ? managed.state : 'OFFLINE' };
  }

  const pid = managed.process.pid;
  const uptime = managed.startedAt ? Math.floor((Date.now() - managed.startedAt.getTime()) / 1000) : 0;
  return { running: true, state: managed.state, pid, uptime };
}

export async function getServerMetrics(uuid: string): Promise<{
  running: boolean;
  cpu: number;
  memory: number; // MB
  maxMemory: number;
  disk: number; // MB
}> {
  const managed = processes.get(uuid);
  if (!managed || !managed.process || !managed.process.pid || managed.state === 'OFFLINE') {
    return { running: false, cpu: 0, memory: 0, maxMemory: 512, disk: 0 };
  }

  try {
    const stats = await pidusage(managed.process.pid);
    return {
      running: true,
      cpu: Math.round(stats.cpu * 10) / 10,
      memory: Math.round((stats.memory / (1024 * 1024)) * 10) / 10,
      maxMemory: managed.config.memory,
      disk: 0,
    };
  } catch {
    return { running: true, cpu: 0, memory: 0, maxMemory: managed.config.memory, disk: 0 };
  }
}
